Repository boostcampwm-2024/and05-MAPISODE, pull requests merged in 2024-12, with the labels that each got.

#167 [CHORE/#166] auth / 나의 에피소드 이름 변경
  feature/episode/src/main/java/com/boostcamp/mapisode/episode/common/NewEpisodeConstant.kt
  feature/home/src/main/res/values/strings.xml
  feature/login/src/main/java/com/boostcamp/mapisode/login/AuthViewModel.kt
Labels: 🛠️ fix

#168 [FIX/#164] : Designsystem / bottom app bar 애니매이션 수정
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/BottomAppBar.kt
Labels: 📱UI/UX, 🛠️ fix

#176 [FIX/#165] Home 에피소드 못 불러오는 에러 해결
  feature/home/src/main/java/com/boostcamp/mapisode/home/HomeViewModel.kt
Labels: 🛠️ fix

#183 [DOCS] 리드미 업데이트
  README.md
Labels: 📄 document

#182 [REFACTOR/#177] 에피소드 생성 화면 중 취소 버튼 클릭시 Dialog 표시하도록 변경
  feature/episode/src/main/java/com/boostcamp/mapisode/episode/ClearDialog.kt
  feature/episode/src/main/java/com/boostcamp/mapisode/episode/NewEpisodeContentScreen.kt
  feature/episode/src/main/java/com/boostcamp/mapisode/episode/NewEpisodeInfoScreen.kt
  feature/episode/src/main/res/values/strings.xml
Labels: 🔧 refactor

#186 [FIX/#153] login / splash 화면 수정
  core/designsystem/src/main/res/drawable-hdpi/ic_mapisode_logo_foreground.png
  core/designsystem/src/main/res/drawable-mdpi/ic_mapisode_logo_foreground.webp
  core/designsystem/src/main/res/drawable-xhdpi/ic_mapisode_logo_foreground.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_mapisode_logo_foreground.png
  core/designsystem/src/main/res/drawable-xxxhdpi/ic_mapisode_logo_foreground.webp
  feature/login/src/main/java/com/boostcamp/mapisode/login/AuthRoute.kt
  feature/login/src/main/java/com/boostcamp/mapisode/login/AuthSideEffect.kt
  feature/login/src/main/java/com/boostcamp/mapisode/login/AuthViewModel.kt
  feature/login/src/main/java/com/boostcamp/mapisode/login/SplashScreen.kt
  feature/login/src/main/java/com/boostcamp/mapisode/login/navigation/AuthNavigation.kt
  feature/main/src/main/java/com/boostcamp/mapisode/main/MainActivity.kt
  feature/main/src/main/java/com/boostcamp/mapisode/main/MainNavigator.kt
  feature/main/src/main/java/com/boostcamp/mapisode/main/component/MainNavHost.kt
Labels: 🛠️ fix

#195 [FEAT/#194] 스로틀링 확장함수 구현
  core/common/src/main/java/com/boostcamp/mapisode/common/util/FlowExt.kt
Labels: ⚙️ feature

#203 [REFACTOR/#202] Group / 사진 Crop으로 띄우기
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/card/GroupInfoCard.kt
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/screen/GroupCreationScreen.kt
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/screen/GroupEditScreen.kt
Labels: 🔧 refactor

#206 [FIX/#155] Group / Toast 추가
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/viewmodel/GroupCreationViewModel.kt
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/viewmodel/GroupDetailViewModel.kt
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/viewmodel/GroupEditViewModel.kt
  feature/mygroup/src/main/res/values/strings.xml
Labels: 🛠️ fix

#207 [FIX/#154] Group / 이미 참여된 그룹 중복 참여 방지
  data/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/GroupRepositoryImpl.kt
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/viewmodel/GroupJoinViewModel.kt
  feature/mygroup/src/main/res/values/strings.xml
Labels: 🛠️ fix

#217 [FIX/#215] Designsystem / 요일 변경
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/datepicker/MapisodeDateSelector.kt
Labels: 🛠️ fix

#213 [FIX/#212] Photopicker / 사진 찍고 나서 다른 곳 선택하면 복사되는 문제 해결
  core/ui/src/main/kotlin/com/boostcamp/mapisode/ui/photopicker/MapisodePhotoPicker.kt
Labels: 🛠️ fix

#216 [FIX/#214] Auth / 구글 버튼 리플 추가
  feature/login/src/main/java/com/boostcamp/mapisode/login/LoginScreen.kt
Labels: 🛠️ fix

#227 [DOCS] 리드미에 스토리 영상 추가
  README.md
Labels: 📄 document
