Repository boostcampwm-2024/and05-MAPISODE, pull requests merged in 2024-11, with the labels that each got.

#10 [FIX] README 역할 삭제
  README.md
Labels: 📄 document

#29 init/#28 : 로고 추가 및 기본 로고 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/ic_mapisode-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_mapisode_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_mapisode.xml
  app/src/main/res/mipmap-anydpi-v26/ic_mapisode_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/ic_mapisode.webp
  app/src/main/res/mipmap-hdpi/ic_mapisode_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_mapisode_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_mapisode.webp
  app/src/main/res/mipmap-mdpi/ic_mapisode_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_mapisode_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_mapisode.webp
  app/src/main/res/mipmap-xhdpi/ic_mapisode_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_mapisode_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_mapisode.webp
  app/src/main/res/mipmap-xxhdpi/ic_mapisode_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_mapisode_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mapisode.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mapisode_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mapisode_round.webp
Labels: ⚡init

#30 [CHORE] README 수정
  README.md
  docs/image/MapisodeMockup.png
Labels: 📄 document

#41 [INIT/#40] login / 모듈 추가
  feature/login/build.gradle.kts
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/boostcamp/mapisode/login/LoginScreen.kt
  settings.gradle.kts
Labels: ⚡init

#52 [FIX/#51] Custom Scaffold 하단 system bar padding 적용
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/MapisodeScaffold.kt
Labels: 🛠️ fix

#97 [FIX/#96] Designsystem / FilledButton 비활성화 텍스트 별도 표시
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/button/MapisodeFilledButton.kt
Labels: 🛠️ fix

#112 [FIX/#111] designsystem / scaffold 시스템바 하단 패딩 수정
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/MapisodeScaffold.kt
Labels: 🛠️ fix

#117 [FIX/#116] Designsystem / FilledButton 크기 modifier 외부에 자유도 부여
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/button/MapisodeFilledButton.kt
Labels: 🛠️ fix

#130 [FIX/#127] Designsystem / OutlintedButton 색상 설정 기능 추가
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/button/MapisodeOutlinedButton.kt
Labels: 🛠️ fix

#135 [FEAT/#133] Designsystem / Custom CircularIndicator 제작
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/MapisodeCircularIndicator.kt
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/theme/ColorScheme.kt
Labels: 📱UI/UX, ⚙️ feature

#137 [FIX/#136] TextField 내부 수정
  core/designsystem/src/main/kotlin/com/boostcamp/mapisode/designsystem/compose/MapisodeTextField.kt
Labels: 📱UI/UX, 🛠️ fix

#143 [FIX/#142] Group / 회원 탈퇴 오류 수정
  data/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/GroupRepositoryImpl.kt
Labels: 🛠️ fix

#148 [FIX/#147] Group / 임시 함수 삭제
  feature/mygroup/src/main/java/com/boostcamp/mapisode/mygroup/viewmodel/GroupJoinViewModel.kt
Labels: 🛠️ fix
